branches:
  only:
  - master

assembly_info:
  patch: false

configuration: Release

platform: Any CPU
  
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  
before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build "src\RadarrAPI" -c %CONFIGURATION% --no-dependencies

cache:
  - '%USERPROFILE%\.nuget\packages'
  
only_commits:
  files:
    - src/
