version: '2'
services:
    mysql:
        image: mysql/mysql-server
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE=radarrupdate
            - MYSQL_USER=root
            - MYSQL_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
          - ./my.cnf:/etc/my.cnf
            
    radarrupdate:
        build: .
        restart: always
        ports:
            - "5000:5000"

        links:
            - mysql

        environment:
            - Radarr:DataDirectory=/data
            - Radarr:Database=server=mysql;user id=root;password=${MYSQL_ROOT_PASSWORD};database=radarrupdate;CharSet=utf8mb4
            - Radarr:ApiKey=test
            - ASPNETCORE_URLS=http://0.0.0.0:5000

        volumes:
            - ./update-data:/data
